### ISSUE TITLE
Why don't you use react functional components and hooks?

### ISSUE THREAD

**Issue by dospolov** [cruip/open-react-template#1]
Hey guys, thanks for the template.

I've bought and worked on your premium template and I'm interested why don't you use react functional components and hooks?
Also, your styling approach does not look elegant (unlike design 👍), have you considered other options? Like CSS frameworks or styled-component

**Comment by reggievick** [comment]
> Hey guys, thanks for the template.
> 
> I've bought and worked on your premium template and I'm interested why don't you use react functional components and hooks?
> Also, your styling approach does not look elegant (unlike design 👍), have you considered other options? Like CSS frameworks or styled-component

I second this. Template is awesome except for what’s under the hood. I would use it and may even buy a premium one if it were using functional  and styled components.

**Comment by pasqualevitiello** [comment]
I've turned class components to functional components, just pushed a commit b00f8839b9dae1350f77bb600765b165e9046006 

We have plans to do the same for our premium templates too, but it might take some time since they include many more components, and it's a quite long process.

To answer the question about styling: there is a solid CSS framework behind our templates. We have seriously considered the _CSS-in-JS_ option, but maintaining an archive of 15+ designs provided in 3 different versions (static HTML, React and Vue) would be a nightmare.
