### ISSUE TITLE
How to change the color of the top right "waves"

### ISSUE THREAD

**Issue by tb47** [cruip/open-react-template#18]
Hi! I struggle for hours to find the color var of theese waves on the top right of the landing page.
Could you please help me out?
Cheers

**Comment by pasqualevitiello** [comment]
Hey @tb47, I am sorry you wasted so much time on this. There is no color var, since illustration is an external SVG files. Open that file and change the HEX color.
<img width="1603" alt="Screenshot 2020-09-05 at 10 11 27 AM" src="https://user-images.githubusercontent.com/2683512/92301041-61818b00-ef60-11ea-98f0-afc214e70c69.png">

**Comment by tb47** [comment]
Dude man Thank you 

Von meinem iPhone gesendet

**Comment by tb47** [comment]
> Hey @tb47, I am sorry you wasted so much time on this. There is no color var, since illustration is an external SVG files. Open that file and change the HEX color.
> <img alt="Screenshot 2020-09-05 at 10 11 27 AM" width="1603" src="https://user-images.githubusercontent.com/2683512/92301041-61818b00-ef60-11ea-98f0-afc214e70c69.png">

Dude, which file is it? :(

**Comment by pasqualevitiello** [comment]
File is illustration-section-01.svg
